package no.novari.flyt.webresourceserver.security.integration.parameters

enum class TestParametersCategory {
    INTERNAL_USER_API_IF_INTERNAL_API_ENABLED,
    INTERNAL_USER_API_IF_INTERNAL_API_DISABLED,
    INTERNAL_ADMIN_API_IF_INTERNAL_API_ENABLED,
    INTERNAL_ADMIN_API_IF_INTERNAL_API_DISABLED,
    INTERNAL_CLIENT_API_IF_ENABLED,
    INTERNAL_CLIENT_API_IF_DISABLED,
    EXTERNAL_CLIENT_API_IF_ENABLED,
    EXTERNAL_CLIENT_API_IF_DISABLED,
    ACTUATOR,
    GLOBAL,
}
