novari:
  cache:
    default-cache-entry-time-to-live: "3530d" # 10 years
    defaultCacheHeapSize: 1000000

spring:
  output:
    ansi:
      enabled: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam