name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            test
            build